devices:
  - host: 192.168.1.1
    device_type: cisco_ios
    username: admin
    password: secure123  # Use env vars in production!
    commands:
      - show interfaces
      - show cdp neighbors detail
      - show version

error_handling:
  retries: 3
  timeout: 10
  log_file: errors.log
